### ISSUE TITLE
process control and load images

### ISSUE THREAD

**Issue by Heyz6** [sealerio/sealer#1456]
sealer Developers：
I have two ideas
1. Can the sealer cluster support process control once it is running. For example, deliver pods to the cluster in batches and support running scripts during the batch delivery process. And the ability to get the current cluster information kubectl interactions.
2. After using Kubefile :_COPY * images produced images also need to docker load images, can you achieve in the production of the image package directly complete the import of the image, do not need to docker load to shorten the cluster installation time (in the image package more, larger scenarios, will shorten the installation time)

**Comment by allencloud** [comment]
Thanks for your great proposal. @Heyz6 

Just my initial thought:
> Can the sealer cluster support process control once it is running

I am afraid NO. Since sealer has its own functional boundary, currently it focuses on **build, share, run CloudImages(ClusterImages)**. While job procedure control may not the target of sealer. And it is the **lifecycle management** of applications or jobs. I prefer that you could use **sealer+ argo( https://github.com/argoproj/argo-workflows )** to implementation what you need. What is more, you could encapsulate all argo related content into your CloudImage, and when running a CloudImage, it could be run the argo workflows to achieve you goal.

> can you achieve in the production of the image package directly complete the import of the image, do not need to docker load to shorten the cluster installation time

I think what you mentioned should be covered in sealer's scope. Good feature request! sealer should automate more things that users do not care, but has not implemented yet.

**Comment by kakaZhou719** [comment]
hi @Heyz6 ，good ideas !  

about "process control " ,my understanding of this is ：sealer could enable user to invoke atomic steps of the bootstrap process, and fill in the gaps if we wish to apply customization by specific running stage.  works like `kubeadm init phase something ` . please feel free to correct me if i am wrong.

**Comment by Heyz6** [comment]
Yes, my understanding is not just kubeadm init phase. For example, for the initialization of the middleware container, I wonder if it could be more flexible, like being able to support shell or python scripts to act on the container when it is delivered to the cluster. I think this should be the hope of many sealer users, and will make it more user-friendly. @kakaZhou719

**Comment by Heyz6** [comment]
Understood, thank you for the solution, I think I will look into argo's solution @allencloud
