### ISSUE TITLE
v1.23 upgrade to v1.24 containerd

### ISSUE THREAD

**Issue by clcc2019** [sealerio/sealer#1731]
I failed to update with upgrade
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/46099295/191877139-f406a4a4-10c6-4ac7-a9cb-d957ac146c4b.png">
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/46099295/191877176-9fd2e421-878c-4427-9d6f-287df602a308.png">

**Comment by allencloud** [comment]
@clcc2019 Currently `sealer upgrade` command has been downgrades to be an alpha command, since the sealer maintainers evaluated sealer community should be pay more energy on stabilize the main commands and have decided to move upgrade command to next phase, at least after the version 1.0.0, maybe in the 1.1.0.
