### ISSUE TITLE
[Bug] sealer will get wrong password when the password carries the $sign

### ISSUE THREAD

**Issue by Starnop** [sealerio/sealer#2077]
### What happen?

When I run `sealer run` with a complicated password that carries the $sign, such as `wjYe$x1yC5xxxx-@8`, the following error will be returned

```
sealer run docker.io/sealerio/kubernetes:v1.22.15 -m 172.28.80.01 -n 172.28.80.02 -p wjYe$x1yC5xxxx-@8
```

![image](https://user-images.githubusercontent.com/31209634/222753865-ca2efd0d-dd51-4ae4-be65-66b2f7cef724.png)

After debugging, I found that the sealer finally received the password value "wjYe-@8".

Everything looks good when I reran the command and added '' to the password, just like this:

```
sealer run docker.io/sealerio/kubernetes:v1.22.15 -m 172.28.80.01 -n 172.28.80.02 -p 'wjYe$x1yC5xxxx-@8'
```

### What is the version of Sealer you using?

```
{"gitVersion":"0.9.1","gitCommit":"3a20cb0d","buildDate":"2023-01-16 12:59:28","goVersion":"go1.17.2","compiler":"gc","platform":"linux/amd64"}
```

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by cubxxw** [comment]
## speculate
Whether `$` was escaped by the shell as an environment variable `\$` instead of being part of the password. Therefore, in order to solve this problem, you need to use single or double quotes around the password to ensure that the password is treated as a string.

## verify
```bash
# version:
❯  /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer version
{"gitVersion":"unknown","gitCommit":"af34af6dd","buildDate":"2023-03-04 04:35:11","goVersion":"go1.19.3","compiler":"gc","platform":"linux/amd64"}
```

## test 
node passwd: 123456

### pass
```bash
❯ /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters  192.168.137.133 --nodes 192.168.137.134 --user root --passwd 123456$safd
```

```bash
❯ /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters  192.168.137.133 --nodes 192.168.137.134 --user root --passwd 123456$safd
```

### failure
```bash
❯ /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters  192.168.137.133 --nodes 192.168.137.134 --user root --passwd 1234ad$safd
```

## Change the node password
```bash
root@etcnode01:~# passwd root
>123456$a
```

### continue to test
```bash
# pass
❯ /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters  192.168.137.133 --nodes 192.168.137.134 --user root --passwd 123456\$a
## AND
❯ /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters  192.168.137.133 --nodes 192.168.137.134 --user root --passwd "123456\$a"
```


# failure
❯ /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters  192.168.137.133 --nodes 192.168.137.134 --user root --passwd 123456$a

## AND
❯ /root/workspces/sealer/_output/bin/sealer/linux_amd64/sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters  192.168.137.133 --nodes 192.168.137.134 --user root --passwd '123456\$a'
```

## bug
https://github.com/sealerio/sealer/blob/af34af6dd29afee1612b1ea16c426d1d18daf6a3/utils/ssh/connect.go#L42
```bash
s.Password = fmt.Sprintf(`"%s"`, passwd)
```
